// Generated by CoffeeScript 2.5.1
// Chromium backend due to matlaget api key difficulties
var parse, puppeteer, scrape, select;

puppeteer = require('puppeteer');

// Parsing
select = function(elem, selector) {
  return elem.querySelector('.menu-item__' + selector).innerText;
};

parse = function(day) {
  return {
    head: select(day, 'heading'),
    desc: select(day, 'description'),
    allergens: select(day, 'list')
  };
};

// Scraping
scrape = async function() {
  var browser, page, week;
  browser = (await puppeteer.launch());
  page = (await browser.newPage());
  await page.goto('https://www.treats.no/');
  await page.waitForSelector('.menu-list');
  week = (await page.evaluate(function() {
    return document.querySelectorAll('.menu-day');
  }));
  //(parse day for day in document.querySelectorAll('.menu-day'))

  //menu = (parseDay day for day in days[...5])
  console.log(week);
  return (await browser.close());
};

scrape();
